CREATE TABLE `matches` (
  `id` int(10) unsigned NOT NULL,
  `region` varchar(4) NOT NULL,
  `winner` enum('100','200') NOT NULL,
  `queue` varchar(45) NOT NULL,
  `map` int(10) unsigned NOT NULL,
  `patch` varchar(15) NOT NULL,
  `creation` datetime NOT NULL,
  `duration` int(10) unsigned NOT NULL,
  `rank` enum('UNRANKED','BRONZE','SILVER','GOLD','PLATINUM','DIAMOND','MASTER','CHALLENGER') NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1

CREATE TABLE `matches_participants` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `match_id` int(10) unsigned NOT NULL,
  `team_id` enum('100','200') NOT NULL,
  `summoner_id` int(10) unsigned NOT NULL,
  `role` enum('?','TOP','JUNGLE','MID','CARRY','SUPPORT') NOT NULL,
  `champion_id` int(10) unsigned NOT NULL,
  `kills` int(10) unsigned NOT NULL,
  `deaths` int(10) unsigned NOT NULL,
  `assists` int(10) unsigned NOT NULL,
  `cs` int(11) unsigned NOT NULL,
  `first_blood` tinyint(3) unsigned NOT NULL,
  `first_tower` tinyint(3) unsigned NOT NULL,
  `largest_kills` int(10) unsigned NOT NULL,
  `largest_spree` int(11) unsigned NOT NULL,
  `spell_d` int(11) unsigned NOT NULL,
  `spell_f` int(11) unsigned NOT NULL,
  `item_0` int(11) unsigned NOT NULL,
  `item_1` int(11) unsigned NOT NULL,
  `item_2` int(11) unsigned NOT NULL,
  `item_3` int(11) unsigned NOT NULL,
  `item_4` int(11) unsigned NOT NULL,
  `item_5` int(11) unsigned NOT NULL,
  `item_6` int(11) unsigned NOT NULL,
  `gold_0_10` int(10) unsigned NOT NULL,
  `gold_0_20` int(10) unsigned NOT NULL,
  `xp_0_10` int(10) unsigned NOT NULL,
  `xp_0_20` int(10) unsigned NOT NULL,
  `double_kills` int(10) unsigned NOT NULL,
  `triple_kills` int(10) unsigned NOT NULL,
  `quadra_kills` int(10) unsigned NOT NULL,
  `penta_kills` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_matches_participants_match_id` (`match_id`),
  KEY `idx_matches_participants_summoner_id` (`summoner_id`),
  CONSTRAINT `fk_matches_participants_match_id` FOREIGN KEY (`match_id`) REFERENCES `matches` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1
