CREATE TABLE `matches` (
  `id` bigint unsigned NOT NULL,
  `region` varchar(4) NOT NULL,
  `winner` tinyint unsigned NOT NULL,
  `queue` varchar(45) NOT NULL,
  `map` tinyint unsigned NOT NULL,
  `patch` varchar(15) NOT NULL,
  `creation` datetime NOT NULL,
  `duration` int unsigned NOT NULL,
  `rank` enum('UNRANKED','BRONZE','SILVER','GOLD','PLATINUM','DIAMOND','MASTER','CHALLENGER') NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `matches_participants` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `match_id` bigint unsigned NOT NULL,
  `team_id` tinyint unsigned NOT NULL,
  `summoner_id` int unsigned NOT NULL,
  `role` enum('?','TOP','JUNGLE','MID','CARRY','SUPPORT') NOT NULL,
  `champion_id` int unsigned NOT NULL,
  `kills` int unsigned NOT NULL,
  `deaths` int unsigned NOT NULL,
  `assists` int unsigned NOT NULL,
  `cs` int unsigned NOT NULL,
  `first_blood` tinyint unsigned NOT NULL,
  `first_tower` tinyint unsigned NOT NULL,
  `first_inhibitor` tinyint unsigned NOT NULL,
  `largest_kill` int unsigned NOT NULL,
  `largest_spree` int unsigned NOT NULL,
  `tower_kills` int unsigned NOT NULL,
  `inhibitor_kills` int unsigned NOT NULL,
  `gold_earned` int unsigned NOT NULL,
  `last_season` enum('UNRANKED','BRONZE','SILVER','GOLD','PLATINUM','DIAMOND','MASTER','CHALLENGER') NOT NULL,
  `spell_d` int unsigned NOT NULL,
  `spell_f` int unsigned NOT NULL,
  `item_0` int unsigned NOT NULL,
  `item_1` int unsigned NOT NULL,
  `item_2` int unsigned NOT NULL,
  `item_3` int unsigned NOT NULL,
  `item_4` int unsigned NOT NULL,
  `item_5` int unsigned NOT NULL,
  `item_6` int unsigned NOT NULL,
  `gold_0_10` int unsigned NOT NULL,
  `gold_10_20` int unsigned NOT NULL,
  `xp_0_10` int unsigned NOT NULL,
  `xp_10_20` int unsigned NOT NULL,
  `double_kills` int unsigned NOT NULL,
  `triple_kills` int unsigned NOT NULL,
  `quadra_kills` int unsigned NOT NULL,
  `penta_kills` int unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_matches_participants_match_id` (`match_id`),
  KEY `idx_matches_participants_summoner_id` (`summoner_id`),
  CONSTRAINT `fk_matches_participants_match_id` FOREIGN KEY (`match_id`) REFERENCES `matches` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
