CREATE TYPE rankType AS ENUM('UNRANKED','BRONZE','SILVER','GOLD','PLATINUM','DIAMOND','MASTER','CHALLENGER');
CREATE TYPE roleType AS ENUM('?','TOP','JUNGLE','MID','CARRY','SUPPORT'),

CREATE TABLE matches (
  id bigint NOT NULL,
  region varchar(4) NOT NULL,
  winner int NOT NULL,
  queue varchar(45) NOT NULL,
  map int NOT NULL,
  season int NOT NULL DEFAULT '7',
  patch_number int NOT NULL DEFAULT '10',
  creation timestamp NOT NULL,
  duration int NOT NULL,
  rank rankType NOT NULL,
  PRIMARY KEY (id, region)
);

CREATE TABLE matches_participants (
  id bigint NOT NULL AUTO_INCREMENT,
  match_id bigint NOT NULL,
  region varchar NOT NULL,
  team_id tinyint NOT NULL,
  summoner_id int NOT NULL,
  role roleType NOT NULL,
  champion_id int NOT NULL,
  kills int NOT NULL,
  deaths int NOT NULL,
  assists int NOT NULL,
  cs int NOT NULL,
  first_blood tinyint NOT NULL,
  first_tower tinyint NOT NULL,
  first_inhibitor tinyint NOT NULL,
  largest_kill int NOT NULL,
  largest_spree int NOT NULL,
  tower_kills int NOT NULL,
  inhibitor_kills int NOT NULL,
  gold_earned int NOT NULL,
  last_season rankType NOT NULL,
  spell_d int NOT NULL,
  spell_f int NOT NULL,
  item_0 int NOT NULL,
  item_1 int NOT NULL,
  item_2 int NOT NULL,
  item_3 int NOT NULL,
  item_4 int NOT NULL,
  item_5 int NOT NULL,
  item_6 int NOT NULL,
  gold_0_10 int NOT NULL,
  gold_10_20 int NOT NULL,
  xp_0_10 int NOT NULL,
  xp_10_20 int NOT NULL,
  double_kills int NOT NULL,
  triple_kills int NOT NULL,
  quadra_kills int NOT NULL,
  penta_kills int NOT NULL,
  PRIMARY KEY (id),
  KEY idx_matches_participants_match_id_region (match_id, region),
  KEY idx_matches_participants_summoner_id (summoner_id),
  KEY idx_matches_participants_match_id_role_team_id (match_id,role,team_id),
  KEY idx_matches_participants_role_champion_id (champion_id,role),
  CONSTRAINT fk_matches_participants_match_id FOREIGN KEY (match_id, region) REFERENCES matches (id, region) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
